version: "3"

services:
  mirthconnect:
    image: kpalang/connect:3.12.0
    container_name: mirthconnect
    environment:
      - DATABASE=postgres
      - DATABASE_URL=jdbc:postgresql://db:5432/mirthconnect
      - DATABASE_MAX_CONNECTIONS=20
      - DATABASE_USERNAME=mirthuser
      - DATABASE_PASSWORD=mirthuserpw
      - KEYSTORE_STOREPASS=docker_storepass
      - KEYSTORE_KEYPASS=docker_keypass
      - VMOPTIONS=-Xmx512m
      - XDG_CONFIG_HOME=/opt/connect/
    networks:
      - private
    ports:
      - 8080:8080/tcp
      - 8443:8443/tcp
      - 6661:6661/tcp
      - 5005:5005/tcp
    volumes:
      - ./extensions:/opt/connect/custom-extensions
      - ./appdata:/opt/connect/appdata
    depends_on:
      - db

  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=mirthdb
      - POSTGRES_PASSWORD=mirthdb
      - POSTGRES_DB=mirthdb
    expose:
      - 5432

networks:
  private:
    external: true
