version: "3"

services:
  mirthconnect:
    image: kpalang/connect:3.12.0
    container_name: mirthconnect
    environment:
      - DATABASE=postgres
      - DATABASE_URL=jdbc:postgresql://db:5432/mirthconnect
      - DATABASE_MAX_CONNECTIONS=20
      - DATABASE_USERNAME=mirthuser
      - DATABASE_PASSWORD=mirthuserpw
      - KEYSTORE_STOREPASS=docker_storepass
      - KEYSTORE_KEYPASS=docker_keypass
      - VMOPTIONS=-Xmx512m
      - XDG_CONFIG_HOME=/opt/connect/
    networks:
      - mirth-network
    ports:
      - 8080:8080/tcp
      - 8443:8443/tcp
      - 6661:6661/tcp
      - 5005:5005/tcp
    volumes:
      - ./extensions:/opt/connect/custom-extensions
      - ./appdata:/opt/connect/appdata
    depends_on:
      - db

  db:
    image: postgres:14.1-alpine
    networks:
      - mirth-network
    ports:
      - 5432
    environment:
      - POSTGRES_USER=mirthuser
      - POSTGRES_PASSWORD=mirthuserpw
      - POSTGRES_DB=mirthconnect
    volumes:
      - ${PWD}/pgdata:/var/lib/postgresql/data

networks:
  mirth-network:
    external: false
